version: "3.9"
services:
  selenium:
    volumes:
      - <keywords.json-directory>:/app/config
    environment:
      - YZ_USERNAME=<yz-username>
      - YZ_PASSWORD=<yz-password>
      - CORP_ID=<wechat-corp-id>
      - CORP_SECRET=<wechat-corp-secret>
      - AGENT_ID=<wechat-agent-id>
      - REDIS_HOST=redis
    links:
      - redis
    image: "hahaleyile/yz"
  redis:
    image: "redis:alpine"
    mem_limit: 200m